name: Build Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create .env
        run: echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" > .env

      - name: Build
        run: npx electron-builder --win --publish never

      - name: Debug - liste dist/
        run: dir dist /s
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: GeoCreuse-Windows
          path: dist/*.exe
          retention-days: 30